int drawCorner(int x, int y, int width, int  height, int colidx)
{
	drawSquare(x,y,1,1,colidx);
	drawSquare(x,y+1,1,1,colidx);
	drawSquare(x,y+2,1,1,colidx);
	drawSquare(x,y+3,1,1,colidx);
	drawSquare(x,y+4,1,1,colidx);
	drawSquare(x,y+5,1,1,colidx);
	drawSquare(x,y+6,1,1,colidx);
	drawSquare(x+1,y,1,1,colidx);
	drawSquare(x+1,y+1,1,1,colidx);
	drawSquare(x+1,y+2,1,1,colidx);
	drawSquare(x+1,y+3,1,1,colidx);
	drawSquare(x+1,y+4,1,1,colidx);
	drawSquare(x+2,y,1,1,colidx);
	drawSquare(x+2,y+1,1,1,colidx);
	drawSquare(x+2,y+2,1,1,colidx);
	drawSquare(x+3,y,1,1,colidx);
	drawSquare(x+3,y+1,1,1,colidx);
	drawSquare(x+4,y,1,1,colidx);
	drawSquare(x+4,y+1,1,1,colidx);
	drawSquare(x+5,y,1,1,colidx);
	drawSquare(x+6,y,1,1,colidx);

	drawSquare(x+ width-1,y,1,1,colidx);
	drawSquare(x+ width-1,y+1,1,1,colidx);
	drawSquare(x+ width-1,y+2,1,1,colidx);
	drawSquare(x+ width-1,y+3,1,1,colidx);
	drawSquare(x+ width-1,y+4,1,1,colidx);
	drawSquare(x+ width-1,y+5,1,1,colidx);
	drawSquare(x+ width-1,y+6,1,1,colidx);
	drawSquare(x+ width-2,y,1,1,colidx);
	drawSquare(x+ width-2,y+1,1,1,colidx);
	drawSquare(x+ width-2,y+2,1,1,colidx);
	drawSquare(x+ width-2,y+3,1,1,colidx);
	drawSquare(x+ width-2,y+4,1,1,colidx);
	drawSquare(x+ width-3,y,1,1,colidx);
	drawSquare(x+ width-3,y+1,1,1,colidx);
	drawSquare(x+ width-3,y+2,1,1,colidx);
	drawSquare(x+ width-4,y,1,1,colidx);
	drawSquare(x+ width-4,y+1,1,1,colidx);
	drawSquare(x+ width-5,y,1,1,colidx);
	drawSquare(x+ width-5,y+1,1,1,colidx);
	drawSquare(x+ width-6,y,1,1,colidx);
	drawSquare(x+ width-7,y,1,1,colidx);

	drawSquare(x,y+ height-1,1,1,colidx);
	drawSquare(x,y+ height-2,1,1,colidx);
	drawSquare(x,y+ height-3,1,1,colidx);
	drawSquare(x,y+ height-4,1,1,colidx);
	drawSquare(x,y+ height-5,1,1,colidx);
	drawSquare(x,y+ height-6,1,1,colidx);
	drawSquare(x,y+ height-7,1,1,colidx);
	drawSquare(x+1,y+ height-1,1,1,colidx);
	drawSquare(x+1,y+ height-2,1,1,colidx);
	drawSquare(x+1,y+ height-3,1,1,colidx);
	drawSquare(x+1,y+ height-4,1,1,colidx);
	drawSquare(x+1,y+ height-5,1,1,colidx);
	drawSquare(x+2,y+ height-1,1,1,colidx);
	drawSquare(x+2,y+ height-2,1,1,colidx);
	drawSquare(x+2,y+ height-3,1,1,colidx);
	drawSquare(x+3,y+ height-1,1,1,colidx);
	drawSquare(x+3,y+ height-2,1,1,colidx);
	drawSquare(x+4,y+ height-1,1,1,colidx);
	drawSquare(x+4,y+ height-2,1,1,colidx);
	drawSquare(x+5,y+ height-1,1,1,colidx);
	drawSquare(x+6,y+ height-1,1,1,colidx);

	drawSquare(x+ width-1,y+ height-1,1,1,colidx);
	drawSquare(x+ width-1,y+ height-2,1,1,colidx);
	drawSquare(x+ width-1,y+ height-3,1,1,colidx);
	drawSquare(x+ width-1,y+ height-4,1,1,colidx);
	drawSquare(x+ width-1,y+ height-5,1,1,colidx);
	drawSquare(x+ width-1,y+ height-6,1,1,colidx);
	drawSquare(x+ width-1,y+ height-7,1,1,colidx);
	drawSquare(x+ width-2,y+ height-1,1,1,colidx);
	drawSquare(x+ width-2,y+ height-2,1,1,colidx);
	drawSquare(x+ width-2,y+ height-3,1,1,colidx);
	drawSquare(x+ width-2,y+ height-4,1,1,colidx);
	drawSquare(x+ width-2,y+ height-5,1,1,colidx);
	drawSquare(x+ width-3,y+ height-1,1,1,colidx);
	drawSquare(x+ width-3,y+ height-2,1,1,colidx);
	drawSquare(x+ width-3,y+ height-3,1,1,colidx);
	drawSquare(x+ width-4,y+ height-1,1,1,colidx);
	drawSquare(x+ width-4,y+ height-2,1,1,colidx);
	drawSquare(x+ width-5,y+ height-1,1,1,colidx);
	drawSquare(x+ width-5,y+ height-2,1,1,colidx);
	drawSquare(x+ width-6,y+ height-1,1,1,colidx);
	drawSquare(x+ width-7,y+ height-1,1,1,colidx);
	return 1;
}
